project:
  type: website
  output-dir: docs

website:
  title: CMSB 2024 (16-18 September, Pisa, Italy)
  search: false
  navbar:
    background: primary
    right:
      - href: https://biomedinfo.di.unipi.it/cmsb2024/
        text: Conference Website
  

format:
  html:
    theme: Cerulean
    toc: false

output:
  html_document:
    keep_md: true